{{- $config := .Values.config | default dict }}
{{- $configMapName := default (printf "%s-config" (include "Discovery-Agent.fullname" .)) $config.configMapName }}
{{- $configFileName := default "config.yaml" $config.fileName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  labels:
    {{- include "Discovery-Agent.labels" . | nindent 4 }}
data:
  {{ $configFileName }}: |
{{ default "log_level: info\nignore_namespaces:\n  - kube-system\nignore_resources:\n  - job/*\n" $config.content | nindent 4 }}
